version: "3.8"

services:
  english-tutor-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: english-tutor-bot
    restart: unless-stopped
    volumes:
      # Volume para persistir dados do bot (logs, etc)
      - bot-data:/app/data
      # Montar .env para facilitar atualizações de configuração
      - ./.env:/app/.env:ro
      # Montar certificado do banco de dados
      - ./db_ca.crt:/app/db_ca.crt:ro
    environment:
      # Variáveis de ambiente adicionais podem ser definidas aqui
      - TZ=America/Sao_Paulo
    networks:
      - bot-network

volumes:
  bot-data:
    name: english-tutor-bot-data

networks:
  bot-network:
    name: english-tutor-network
